# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_jbPo_n7PjeHxDeRW__sl1aSpc5RMcB8
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from google.colab import files

uploaded = files.upload()

df = pd.read_csv('dhaka homeprices.csv')
df

# df.head(6)

# df.shape

# df.isnull().any()

df.isnull().sum()

# Plot
plt.xlabel('Area in square ft')
plt.ylabel('Price in taka')
plt.scatter(df['area'], df['price'],color='red', marker='+')
plt.title('Homeprices in Dhaka city')
plt.plot()

# Separate dependent and independent variable
x = df[['area']]
x
y = df['price']
y

# Split Data set
from sklearn.model_selection import train_test_split

xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.25, random_state =1)

xtest

xtrain

ytrain

ytest

# Fitting Multiple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()

regressor.fit(xtrain, ytrain)

regressor.predict(xtest)

regressor.predict([[3500]])

# Plot
plt.xlabel('Area in square ft')
plt.ylabel('Price in taka')
plt.scatter(df['area'], df['price'],color='red', marker='+')
plt.title('Homeprices in Dhaka city')
plt.plot(df.area,regressor.predict(df[['area']]))

a = regressor.intercept_

b = regressor.coef_
a

b

# Y = MX + C , x = 3500
y = b*3500 + a

y